DROP TABLE CUSTOMERS;
CREATE TABLE CUSTOMERS(
    USER_ID                 VARCHAR(40) NOT NULL,
    CUSTOMER_ID             VARCHAR(40) NOT NULL,
    CUSTOMER_Name           VARCHAR(40) NOT NULL,
    CUSTOMER_SPENT_MONEY    INT         NOT NULL,
    CUSTOMER_PURCHASE_COUNT INT         NOT NULL,
    PRIMARY KEY (CUSTOMER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

INSERT INTO CUSTOMERS VALUES ('a','customerA','손님A',50000,2);
INSERT INTO CUSTOMERS VALUES ('a','customerB','손님B',120000,3);
INSERT INTO CUSTOMERS VALUES ('a','customerC','손님C',500000,12);
INSERT INTO CUSTOMERS VALUES ('b','customer1','손님1',530000,11);
INSERT INTO CUSTOMERS VALUES ('b','customer2','손님2',12000,1);
INSERT INTO CUSTOMERS VALUES ('b','customer3','손님3',100000,1);
UPDATE CUSTOMERS SET CUSTOMER_NAME = '손님A',CUSTOMER_SPENT_MONEY = 50000,CUSTOMER_PURCHASE_COUNT = 2 WHERE CUSTOMER_ID='customerA';

SELECT * FROM CUSTOMERS;

DELETE FROM CUSTOMERS WHERE USER_ID = 'a' AND CUSTOMER_ID = 'customerB';