DROP TABLE CUSTOMERS;
CREATE TABLE CUSTOMERS(
    USER_ID                 VARCHAR(20) NOT NULL,
    CUSTOMER_ID             VARCHAR(20) NOT NULL,
    CUSTOMER_Name           VARCHAR(20) NOT NULL,
    CUSTOMER_SPENT_MONEY    INT         NOT NULL,
    CUSTOMER_PURCHASE_COUNT INT         NOT NULL,
    PRIMARY KEY (CUSTOMER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);