CREATE TABLE USERS(
    USER_ID VARCHAR(40) NOT NULL,
    USER_PASSWORD VARCHAR(40) NOT NULL,
    USER_EMAIL VARCHAR(40) NOT NULL,
    USER_NAME VARCHAR(40) NOT NULL,
    USER_STORE_NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (USER_ID)
);

INSERT INTO USERS VALUES ('a','a1234','a@gmail.com','이규석','VINSDAY');
INSERT INTO USERS VALUES ('b','b1234','b@gmail.com','이연진','무신사');
update USERS set USER_PASSWORD = 'a1234',USER_NAME = '규석' where USER_ID = 'a';

SELECT * FROM USERS;

DELETE FROM USERS WHERE USER_ID = 'h';