CREATE TABLE USERS(
    USER_ID VARCHAR(20) NOT NULL,
    USER_PASSWORD VARCHAR(20) NOT NULL,
    USER_EMAIL VARCHAR(20) NOT NULL,
    USER_NAME VARCHAR(20) NOT NULL,
    USER_STORE_NAME VARCHAR(20) NOT NULL,
    PRIMARY KEY (USER_ID)
);

INSERT INTO USERS VALUES ('a','a1234','a@gmail.com','이규석','VINSDAY');
INSERT INTO USERS VALUES ('b','b1234','b@gmail.com','이연진','무신사');


SELECT * FROM USERS;